In [1]:
import numpy as np
A = np.array([[2.0, 1.0],[1.0, 3.0]])
b = np.array([1.0, 2.0])
print("Matrix A:\n", A)
print("\nTranspose A^T:\n", A.T)
print("\nInverse A^-1:\n", np.linalg.inv(A))
eigvals, eigvecs = np.linalg.eig(A)
print("\nEigenvalues:", np.round(eigvals,4))
x = np.linalg.solve(A,b)
print("\nSolve A x = b --> x:", np.round(x,4))

Matrix A:
 [[2. 1.]
 [1. 3.]]

Transpose A^T:
 [[2. 1.]
 [1. 3.]]

Inverse A^-1:
 [[ 0.6 -0.2]
 [-0.2  0.4]]

Eigenvalues: [1.382 3.618]

Solve A x = b --> x: [0.2 0.6]
